import sys
import os

sys.path.insert(0, r"c:\Users\ssakesh\Downloads\DHARA-GX\Agent Dhara Backend")

from agent.session_store import load_session

session_id = "5881a9d5-c5fe-4e17-b50a-bb18b358ae2b"
session = load_session(session_id)
context = session.get("context", {})
etl_flow = context.get("etl_flow", {})

print("Phase:", etl_flow.get("phase"))
print("Generated by:", etl_flow.get("generated_by"))
print("Validation OK:", etl_flow.get("validation_ok"))
print("Validation Errors:", etl_flow.get("validation_errors"))
print("Artifact path:", etl_flow.get("artifact_rel_path"))
