'use client';

import { useState, useEffect, useCallback } from 'react';
import { motion } from 'framer-motion';
import { FaCode, FaCopy, FaCheck, FaThumbsUp, FaThumbsDown, FaDownload, FaDatabase, FaUpload, FaEdit } from 'react-icons/fa';
import { SiPython, SiApachespark } from 'react-icons/si';

interface ETLCodeGeneratorProps {
  files: string[];
  assessmentData: any;
  businessRequirements?: string;
  onGenerated: (code: string) => void;
  onNext: () => void;
  onFeedback: (liked: boolean, comment?: string) => void;
}

export default function ETLCodeGenerator({ files, assessmentData, businessRequirements, onGenerated, onNext, onFeedback }: ETLCodeGeneratorProps) {
  const [generating, setGenerating] = useState(true);
  const [progress, setProgress] = useState(0);
  const [selectedLanguage, setSelectedLanguage] = useState<'python' | 'spark' | 'sql'>('python');
  const [generatedCode, setGeneratedCode] = useState('');
  const [copied, setCopied] = useState(false);
  const [showOptions, setShowOptions] = useState(false);
  const [isEditing, setIsEditing] = useState(false);

  const getCodeTemplate = (language: string) => {
    const req = (businessRequirements ?? '').trim();
    const reqHeader = req
      ? `# Business requirements (user provided)\n# ${req.replace(/\n/g, '\n# ')}\n\n`
      : '';

    const pythonCode = `import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from datetime import datetime

${reqHeader}# Generated by Agent DHARA

class DataETL:
    def __init__(self, connection_string):
        self.engine = create_engine(connection_string)
        self.data_frames = {}
        
    def extract_data(self):
        """Extract data from database"""
        print("Starting data extraction...")
        ${files.map(file => `
        # Extract ${file}
        self.data_frames['${file}'] = pd.read_sql_table('${file}', self.engine)
        print(f"Extracted {len(self.data_frames['${file}'])} rows from ${file}")
        `).join('\n        ')}
        
    def transform_data(self):
        """Transform and clean data"""
        print("Starting data transformation...")
        
        for table_name, df in self.data_frames.items():
            print(f"\\nTransforming {table_name}...")
            
            # Remove duplicates
            before_count = len(df)
            df = df.drop_duplicates()
            print(f"  - Removed {before_count - len(df)} duplicates")
            
            # Handle missing values
            for col in df.columns:
                null_count = df[col].isnull().sum()
                if null_count > 0:
                    if df[col].dtype in ['float64', 'int64']:
                        df[col].fillna(df[col].median(), inplace=True)
                    else:
                        df[col].fillna(df[col].mode()[0] if not df[col].mode().empty else 'Unknown', inplace=True)
                    print(f"  - Filled {null_count} missing values in {col}")
            
            # Data type conversions
            for col in df.columns:
                if 'date' in col.lower() or 'time' in col.lower():
                    try:
                        df[col] = pd.to_datetime(df[col])
                        print(f"  - Converted {col} to datetime")
                    except:
                        pass
            
            self.data_frames[table_name] = df
            
    def load_data(self, output_connection_string):
        """Load cleaned data to destination"""
        print("\\nLoading data to destination...")
        output_engine = create_engine(output_connection_string)
        
        for table_name, df in self.data_frames.items():
            df.to_sql(f'{table_name}_cleaned', output_engine, if_exists='replace', index=False)
            print(f"Loaded {len(df)} rows to {table_name}_cleaned")
            
    def generate_quality_report(self):
        """Generate data quality report"""
        report = {
            'timestamp': datetime.now().isoformat(),
            'tables': {}
        }
        
        for table_name, df in self.data_frames.items():
            report['tables'][table_name] = {
                'row_count': len(df),
                'column_count': len(df.columns),
                'missing_values': df.isnull().sum().sum(),
                'duplicate_rows': df.duplicated().sum(),
                'memory_usage': df.memory_usage(deep=True).sum() / 1024**2  # MB
            }
            
        return report

# Usage
if __name__ == "__main__":
    etl = DataETL('postgresql://user:password@localhost:5432/database')
    etl.extract_data()
    etl.transform_data()
    etl.load_data('postgresql://user:password@localhost:5432/cleaned_database')
    report = etl.generate_quality_report()
    print("\\nETL Process Complete!")
    print(report)
`;

    const sparkCode = `from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.types import *

class SparkETL:
    def __init__(self):
        self.spark = SparkSession.builder \\
            .appName("DataETL") \\
            .config("spark.sql.adaptive.enabled", "true") \\
            .getOrCreate()
        self.dataframes = {}
        
    def extract_data(self, jdbc_url, properties):
        """Extract data from database"""
        print("Starting data extraction...")
        ${files.map(file => `
        # Extract ${file}
        self.dataframes['${file}'] = self.spark.read.jdbc(
            url=jdbc_url,
            table='${file}',
            properties=properties
        )
        print(f"Extracted {self.dataframes['${file}'].count()} rows from ${file}")
        `).join('\n        ')}
        
    def transform_data(self):
        """Transform and clean data"""
        print("Starting data transformation...")
        
        for table_name, df in self.dataframes.items():
            print(f"\\nTransforming {table_name}...")
            
            # Remove duplicates
            df = df.dropDuplicates()
            
            # Handle missing values
            for col_name in df.columns:
                col_type = df.schema[col_name].dataType
                if isinstance(col_type, (IntegerType, DoubleType, FloatType)):
                    median_val = df.approxQuantile(col_name, [0.5], 0.01)[0]
                    df = df.fillna({col_name: median_val})
                else:
                    df = df.fillna({col_name: 'Unknown'})
            
            self.dataframes[table_name] = df
            
    def load_data(self, jdbc_url, properties):
        """Load cleaned data"""
        print("\\nLoading data to destination...")
        
        for table_name, df in self.dataframes.items():
            df.write.jdbc(
                url=jdbc_url,
                table=f'{table_name}_cleaned',
                mode='overwrite',
                properties=properties
            )
            print(f"Loaded {df.count()} rows to {table_name}_cleaned")

# Usage
if __name__ == "__main__":
    etl = SparkETL()
    jdbc_url = "jdbc:postgresql://localhost:5432/database"
    properties = {"user": "username", "password": "password", "driver": "org.postgresql.Driver"}
    
    etl.extract_data(jdbc_url, properties)
    etl.transform_data()
    etl.load_data(jdbc_url, properties)
    print("\\nETL Process Complete!")
`;

    const sqlCode = `-- ETL SQL Script
-- Extract, transform and load data using SQL

-- Step 1: Create staging/cleaned tables (remove duplicates, handle nulls)
${files.map(file => `
-- Process ${file}
CREATE TABLE ${file}_cleaned AS
SELECT DISTINCT *
FROM ${file};

-- Optional: Update nulls in ${file}_cleaned
-- UPDATE ${file}_cleaned SET column_name = COALESCE(column_name, default_value) WHERE column_name IS NULL;
`).join('\n')}

-- Step 2: Create summary view for reporting
CREATE OR REPLACE VIEW etl_summary AS
${files.map((file, i) => `SELECT '${file}' AS source_table, COUNT(*) AS row_count FROM ${file}_cleaned${i < files.length - 1 ? '\nUNION ALL' : ''}`).join('\n')};

-- Step 3: Load to destination (example: insert into target schema)
${files.map(file => `
-- INSERT INTO target_schema.${file} SELECT * FROM ${file}_cleaned;
`).join('')}

-- Execute in order: run each section against your database
`;

    return language === 'python' ? pythonCode : language === 'spark' ? sparkCode : sqlCode;
  };

  // getCodeTemplate uses files + businessRequirements from closure
  // eslint-disable-next-line react-hooks/exhaustive-deps -- getCodeTemplate is recreated when those deps change
  const generateCode = useCallback(async () => {
    setGenerating(true);
    setProgress(0);
    for (let i = 0; i <= 100; i += 10) {
      await new Promise((resolve) => setTimeout(resolve, 150));
      setProgress(i);
    }
    const code = getCodeTemplate(selectedLanguage);
    setGeneratedCode(code);
    setGenerating(false);
    onGenerated(code);
  }, [selectedLanguage, files, businessRequirements, onGenerated]);

  useEffect(() => {
    void generateCode();
  }, [generateCode]);

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleUpload = () => {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.py,.sql,.txt';
    input.onchange = (e) => {
      const file = (e.target as HTMLInputElement).files?.[0];
      if (!file) return;
      const reader = new FileReader();
      reader.onload = () => {
        const text = reader.result as string;
        setGeneratedCode(text);
        onGenerated(text);
      };
      reader.readAsText(file);
    };
    input.click();
  };

  const handleEditToggle = () => {
    setIsEditing(!isEditing);
    if (isEditing) onGenerated(generatedCode);
  };

  const handleDownload = () => {
    const extension = selectedLanguage === 'sql' ? 'sql' : selectedLanguage === 'spark' ? 'py' : 'py';
    const blob = new Blob([generatedCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `etl_code.${extension}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleLike = () => {
    onFeedback(true);
    setShowOptions(true);
  };

  const handleDislike = () => {
    const comment = prompt('What would you like us to improve in the ETL code?');
    onFeedback(false, comment || undefined);
    
    setTimeout(() => {
      alert('Thank you! Regenerating improved ETL code...');
      generateCode();
    }, 500);
  };

  if (generating) {
    return (
      <div className="flex flex-col items-center justify-center space-y-10 py-16">
        <div className="relative">
          <div className="absolute inset-0 scale-150 blur-3xl bg-gradient-to-tr from-[#12ABDB]/20 to-[#0070AD]/20 animate-pulse" />
          <div className="relative flex h-24 w-24 items-center justify-center rounded-3xl bg-white shadow-2xl">
            <FaCode className="text-4xl text-[#0070AD] animate-bounce" />
          </div>
        </div>
        
        <div className="text-center space-y-3">
          <h2 className="text-4xl font-black tracking-tight text-zinc-900">Engineering Pipeline</h2>
          <p className="text-lg font-medium text-black/40">Architecting optimized ETL logic based on your requirements...</p>
        </div>

        <div className="w-full max-w-md space-y-4">
          <div className="relative h-3 w-full bg-black/5 rounded-full overflow-hidden border border-black/5">
            <motion.div
              className="h-full bg-gradient-to-r from-[#12ABDB] via-[#0070AD] to-[#12ABDB] bg-[length:200%_auto]"
              initial={{ width: 0 }}
              animate={{ width: `${progress}%`, backgroundPosition: ['0% 0%', '100% 0%'] }}
              transition={{ width: { duration: 0.5 }, backgroundPosition: { duration: 2, repeat: Infinity, ease: 'linear' } }}
            />
          </div>
          <div className="flex items-center justify-between px-1">
            <span className="text-[11px] font-black uppercase tracking-widest text-black/30">Generation Progress</span>
            <span className="text-xl font-black text-[#12ABDB]">{progress}%</span>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold text-zinc-900 mb-2">ETL Code Generated</h2>
          <p className="text-black/60">Review and download your ETL pipeline code</p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={handleLike}
            className="p-3 bg-[#0070AD]/10 text-[#0070AD] rounded-lg hover:bg-[#0070AD]/15 transition-colors"
          >
            <FaThumbsUp className="text-xl" />
          </button>
          <button
            onClick={handleDislike}
            className="p-3 bg-red-500/20 text-red-400 rounded-lg hover:bg-red-500/30 transition-colors"
          >
            <FaThumbsDown className="text-xl" />
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        {[
          { id: 'python', label: 'Python / Pandas', icon: SiPython, desc: 'Optimized for memory & local dev' },
          { id: 'spark', label: 'Apache PySpark', icon: SiApachespark, desc: 'Scaled for Big Data clusters' },
          { id: 'sql', label: 'T-SQL / SQL', icon: FaDatabase, desc: 'In-database transformation' },
        ].map(({ id, label, icon: Icon, desc }) => (
          <button
            key={id}
            onClick={() => setSelectedLanguage(id as any)}
            className={`group relative flex flex-col gap-3 rounded-2xl border p-5 text-left transition-all duration-300 ${
              selectedLanguage === id
                ? 'border-[#0070AD] bg-gradient-to-br from-[#0070AD] to-[#12ABDB] text-white shadow-xl shadow-[#0070AD]/20'
                : 'border-black/10 bg-white/80 text-zinc-900 hover:border-[#0070AD]/40 hover:bg-white'
            }`}
          >
            <div className={`flex h-10 w-10 items-center justify-center rounded-xl transition-colors ${
              selectedLanguage === id ? 'bg-white/20' : 'bg-[#0070AD]/10 text-[#0070AD]'
            }`}>
              <Icon className="text-xl" />
            </div>
            <div>
              <div className="text-sm font-black tracking-tight">{label}</div>
              <div className={`text-[11px] font-medium leading-tight ${selectedLanguage === id ? 'text-white/70' : 'text-black/40'}`}>
                {desc}
              </div>
            </div>
            {selectedLanguage === id && (
              <div className="absolute right-4 top-4">
                <FaCheck className="text-xs" />
              </div>
            )}
          </button>
        ))}
      </div>

      {/* Code Header and Actions */}
      <div className="flex flex-wrap items-center justify-between gap-4 border-t border-black/5 pt-6">
        <div className="flex flex-wrap gap-2.5">
          <motion.button
            onClick={handleDownload}
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            className="flex items-center gap-2 rounded-xl border border-black/10 bg-white px-4 py-2 text-[12px] font-black text-zinc-800 shadow-sm transition-all hover:border-[#0070AD] hover:bg-zinc-50"
          >
            <FaDownload className="text-[#0070AD]" />
            <span>EXPORT . {selectedLanguage.toUpperCase()}</span>
          </motion.button>
          <motion.button
            onClick={handleEditToggle}
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            className={`flex items-center gap-2 rounded-xl border px-4 py-2 text-[12px] font-black transition-all shadow-sm ${
              isEditing 
                ? 'border-[#0070AD] bg-[#0070AD] text-white' 
                : 'border-black/10 bg-white text-zinc-800 hover:border-[#0070AD]'
            }`}
          >
            <FaEdit className={isEditing ? 'text-white' : 'text-[#0070AD]'} />
            <span>{isEditing ? 'COMMIT EDITS' : 'MANUAL EDIT'}</span>
          </motion.button>
        </div>
        
        <div className="flex gap-2">
          <button
            onClick={handleCopy}
            className={`flex items-center gap-2 rounded-xl px-5 py-2 text-[12px] font-black tracking-widest uppercase transition-all ${
              copied ? 'bg-emerald-500 text-white' : 'bg-zinc-900 text-white hover:bg-zinc-800'
            }`}
          >
            {copied ? <FaCheck /> : <FaCopy />}
            <span>{copied ? 'COPIED!' : 'COPY CODE'}</span>
          </button>
        </div>
      </div>

      {/* Code Area */}
      <div className="group relative overflow-hidden rounded-2xl border border-black/20 bg-[#0d1117] shadow-2xl">
        <div className="flex items-center justify-between border-b border-white/10 bg-white/5 px-4 py-3">
          <div className="flex gap-1.5">
            <div className="h-2.5 w-2.5 rounded-full bg-[#ff5f56]" />
            <div className="h-2.5 w-2.5 rounded-full bg-[#ffbd2e]" />
            <div className="h-2.5 w-2.5 rounded-full bg-[#27c93f]" />
          </div>
          <div className="text-[11px] font-black tracking-widest text-white/30 uppercase">
            {selectedLanguage === 'python' ? 'pandas_pipeline.py' : selectedLanguage === 'spark' ? 'spark_session.py' : 'transform.sql'}
          </div>
        </div>
        
        <div className="max-h-[500px] overflow-auto">
          {isEditing ? (
            <textarea
              value={generatedCode}
              onChange={(e) => setGeneratedCode(e.target.value)}
              className="w-full bg-transparent p-6 font-mono text-[13px] text-blue-100/90 outline-none resize-none min-h-[400px]"
              spellCheck={false}
            />
          ) : (
            <pre className="p-6 font-mono text-[13px] leading-relaxed text-blue-100/80">
              <code>{generatedCode}</code>
            </pre>
          )}
        </div>
      </div>

      {/* Options */}
      {showOptions && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-4"
        >
          <div className="p-6 bg-white/90 border border-black/10 rounded-lg">
            <h3 className="text-xl font-bold text-zinc-900 mb-4">Would you like to work on duplicate data?</h3>
            <p className="text-black/60 mb-4">
              We can help clean your data and remove duplicates before running the ETL process.
            </p>
            <div className="flex flex-wrap gap-4">
              <button
                onClick={onNext}
                className="px-6 py-3 bg-[#0070AD] text-white rounded-xl font-semibold hover:bg-[#12ABDB] transition-colors"
              >
                Yes, Clean My Data
              </button>
              <button
                onClick={() => alert('Code is ready to use! Download and run it in your environment.')}
                className="px-6 py-3 bg-white border border-black/10 text-zinc-900 rounded-xl font-semibold hover:border-[#0070AD]/30 transition-colors"
              >
                No, Code is Enough
              </button>
            </div>
          </div>
        </motion.div>
      )}
    </div>
  );
}
