from __future__ import annotations

import re
from typing import Any, Dict, List, Optional


def _safe_ident(name: str) -> str:
    s = re.sub(r"[^0-9a-zA-Z_]+", "_", name)
    if s and s[0].isdigit():
        s = "ds_" + s
    return s or "dataset"


def _col_expr(col: str) -> str:
    return repr(str(col))


def _emit_step(action: str, col: Optional[str], ds_var: str) -> List[str]:
    lines: List[str] = []
    if not col:
        if action == "deduplicate":
            lines.append(f"{ds_var} = {ds_var}.drop_duplicates()")
        return lines

    c = _col_expr(col)
    if action == "trim":
        lines.append(f"{ds_var}[{c}] = {ds_var}[{c}].astype(str).str.strip()")
    elif action in ("fill_or_drop", "fill_nulls_simple"):
        lines.append(f"{ds_var}[{c}] = {ds_var}[{c}].fillna('')")
    elif action == "coerce_numeric":
        lines.append(f"{ds_var}[{c}] = pd.to_numeric({ds_var}[{c}], errors='coerce')")
    elif action == "parse_dates":
        lines.append(f"{ds_var}[{c}] = pd.to_datetime({ds_var}[{c}], errors='coerce')")
    elif action == "sanitize_email":
        lines.append(f"{ds_var}[{c}] = {ds_var}[{c}].astype(str).str.strip().str.lower()")
        lines.append(f"_bad = ~{ds_var}[{c}].str.contains('@', na=False); {ds_var}.loc[_bad, {c}] = pd.NA")
    elif action == "normalize_phone":
        lines.append(f"{ds_var}[{c}] = {ds_var}[{c}].astype(str).str.replace(r'\\D', '', regex=True)")
    elif action == "lowercase":
        lines.append(f"{ds_var}[{c}] = {ds_var}[{c}].astype(str).str.lower()")
    elif action == "uppercase":
        lines.append(f"{ds_var}[{c}] = {ds_var}[{c}].astype(str).str.upper()")
    elif action == "standardize_boolean":
        lines.append(f"_v = {ds_var}[{c}].astype(str).str.strip().str.lower()")
        lines.append(f"{ds_var}[{c}] = _v.isin(('1', 'true', 'yes', 'y', 't')).astype('Int64')")
    elif action == "deduplicate":
        lines.append(f"{ds_var} = {ds_var}.drop_duplicates(subset=[{c}], keep='first')")
    elif action in ("regex_replace", "clip_or_flag", "range_clip", "replace_values", "zero_to_null"):
        lines.append(f"# TODO: {action} on column {c} — implement with business approval")
    elif action == "validate_referential_integrity_or_stage":
        lines.append(f"# Referential integrity involving {c} — validate in staging/warehouse")
    else:
        lines.append(f"# Unsupported in codegen v1: {action} ({c})")
    return lines


def generate_python_etl(plan: Dict[str, Any], assessment: Dict[str, Any]) -> str:
    """Generate one transform_* function per dataset in the plan."""
    _ = assessment  # reserved for future: dtypes / paths from assessment
    plan_id = str(plan.get("plan_id") or "unknown")
    lines: List[str] = [
        '"""',
        f"ETL generated by Agent Dhara — plan_id={plan_id}",
        "Review manual_review items before running in production.",
        '"""',
        "from __future__ import annotations",
        "",
        "import pandas as pd",
        "",
    ]

    notes = (plan.get("business_rules") or {}).get("notes") or ""
    if notes:
        lines.extend(["# Business notes (from user):", "# " + str(notes).replace("\n", "\n# "), ""])

    ds_plan = plan.get("datasets") or {}
    for ds_name, block in ds_plan.items():
        fn = f"transform_{_safe_ident(ds_name)}"
        lines.append(f"def {fn}(df: pd.DataFrame) -> pd.DataFrame:")
        lines.append('    """Apply planned cleaning transforms."""')
        ds_var = "out"
        lines.append(f"    {ds_var} = df.copy()")
        for st in sorted(block.get("steps") or [], key=lambda x: int(x.get("order") or 0)):
            for sl in _emit_step(str(st.get("action")), st.get("column"), ds_var):
                lines.append(f"    {sl}")
        lines.append(f"    return {ds_var}")
        lines.append("")

    lines.append("DATASET_NAMES = " + repr(list(ds_plan.keys())))
    lines.append("")
    lines.append("if __name__ == '__main__':")
    lines.append("    print('Defines transform_* functions — import from your pipeline.')")
    lines.append("")

    return "\n".join(lines)
